server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # CORS géré ici, une seule fois, pour tous les services
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://maison-noura-brown.vercel.app"
              - "https://*.vercel.app"
            allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: catalog-service
          uri: ${CATALOG_URI:http://localhost:8081}
          predicates:
            - Path=/api/categories/**,/api/prestations/**
        - id: booking-service
          uri: ${BOOKING_URI:http://localhost:8082}
          predicates:
            - Path=/api/appointments/**,/api/slots/**

# Validation des tokens JWT émis par Keycloak (realm "maison-noura")
keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/maison-noura}
  jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/maison-noura/protocol/openid-connect/certs}
